/**
 * MindBody session type names, frozen from the 2026-09-18 API snapshot.
 * mb_appointments_history stores only session_type_id for MindBody rows, and the
 * API goes away with the cancellation, so the names live here.
 */
export const MINDBODY_SESSION_TYPE_NAMES: Record<number, string> = {
    5: "New Botox Patient",
    6: "New Dysport Patient",
    9: "Sculptra Butt",
    10: "Complementary Consult with a Nurse Practitioner",
    16: "Dermaplaning",
    17: "Platelet Rich Plasma (PRP)",
    18: "Sculptra Facial Aesthetics",
    23: "Urinary Incontinence",
    24: "HydraFacial",
    46: "Complementary Consult with an Aesthetician",
    47: "Skin Tightening - Abdomen",
    48: "Skin Tightening - Arm",
    49: "Skin Tightening - Bra/Back",
    50: "Skin Tightening - Buttocks",
    51: "Skin Tightening - Flank",
    52: "Skin Tightening - Thighs",
    53: "Hair Removal - Small Area",
    54: "Hair Removal - Medium Area",
    55: "Hair Removal - Large Area",
    56: "Hair Removal - XL Area",
    57: "Skin Rejuvenation - Face",
    58: "Skin Rejuvenation - Neck",
    60: "Skin Rejuvenation - Chest",
    64: "Chemical Peel",
    66: "Platysmal Bands",
    67: "Subcisions",
    69: "Radio Frequency (RF) Microneedling",
    78: "Dissolve Filler",
    85: "Lip Filler",
    86: "Midface Filler",
    87: "Chin Filler",
    88: "Profile Balancing",
    89: "Skin Pen Microneedling",
    90: "Body Sculpting with Emsculpt Neo",
    92: "Hair Rejuvenation with PRP",
    93: "Double Chin Concern",
    97: "Existing Botox Patient",
    98: "Existing Dysport Patient",
    99: "Follow Up",
    100: "Follow Up",
    101: "Weight Loss Consultation",
    102: "Semaglutide",
    103: "Tirzepatide",
    104: "Test GHL Appointment",
    105: "Cool peel",
    106: "Platelet-Derived Growth Factor (PDGF)",
    107: "Membership SB Peel",
    108: "Membership Dermaplaning Facial",
};
